<?php
/*
 * Copyright (c) 2026 White Knight Roadside, LLC. All Rights Reserved.
 *
 * Proprietary and confidential. This software is LICENSED, NOT SOLD.
 * Unauthorized copying, modification, distribution, or use of this file,
 * via any medium, is strictly prohibited and will be prosecuted to the
 * fullest extent of the law (17 U.S.C. Sections 501-505). See LICENSE.txt.
 * Licensing: licensing@wkrllc.com
 */
declare(strict_types=1);

/**
 * Every third-party dependency sits behind one of these. The application only
 * ever talks to the interface, so swapping a driver is a line in config.php and
 * a class in app/Services — nothing in the business logic moves.
 *
 * Webhook verification is part of the contract rather than the controller: only
 * the driver knows how its provider signs a callback, and an unverified callback
 * must never reach the business logic.
 */

/**
 * Result of any integration call. Never throws at the caller.
 *
 * Treat every property as read-only. They are not declared `readonly` because
 * that keyword is PHP 8.1+, and the floor here is 8.0 so the application runs on
 * a stock PHP install without an upgrade first.
 */
final class IntegrationResult
{
    public function __construct(
        public bool $ok,
        public string $reference = '',
        public string $message = '',
        public array $raw = []
    ) {}

    public static function ok(string $reference = '', array $raw = []): self
    {
        return new self(true, $reference, '', $raw);
    }

    public static function fail(string $message, array $raw = []): self
    {
        return new self(false, '', $message, $raw);
    }
}

interface SmsGateway
{
    /** @param string $to E.164 */
    public function send(string $to, string $body, array $meta = []): IntegrationResult;

    public function driverName(): string;

    /** False when the gateway is not configured — the outbox still records the message. */
    public function isLive(): bool;

    /**
     * Confirms a callback really came from the provider. Anything that fails
     * this is dropped before it is parsed.
     *
     * @param array<string,string> $headers lower-cased
     */
    public function verifyWebhook(string $rawBody, array $headers): bool;

    /**
     * Normalises a provider callback into a shape the application understands.
     *
     * @return array{kind:string, reference:string, from:string, to:string, text:string, status:string}|null
     *         kind is 'inbound' | 'status'
     */
    public function parseWebhook(string $rawBody): ?array;
}

interface PaymentGateway
{
    /**
     * The idempotency key is always generated by the caller, before this is
     * invoked, so a retry can never become a second charge.
     */
    public function charge(float $amount, string $idempotencyKey, array $meta = []): IntegrationResult;

    /**
     * A hosted page the customer can pay on, for card payments taken without a
     * terminal. The reference returned is the provider's order id, which the
     * webhook uses to match the payment back to the invoice.
     */
    public function paymentLink(float $amount, string $idempotencyKey, array $meta = []): IntegrationResult;

    public function refund(string $paymentReference, float $amount, string $idempotencyKey): IntegrationResult;

    public function driverName(): string;

    public function isLive(): bool;

    /** @param array<string,string> $headers lower-cased */
    public function verifyWebhook(string $rawBody, array $headers): bool;

    /**
     * @return array{kind:string, reference:string, order_id:string, amount:float, status:string, method:string}|null
     *         kind is 'payment' | 'refund'
     */
    public function parseWebhook(string $rawBody): ?array;
}

interface VinDecoder
{
    /** @return array<string,mixed> decoded attributes; empty array if it cannot decode */
    public function decode(string $vin): array;

    public function driverName(): string;
}

interface Geocoder
{
    /** @return array{lat:?float,lng:?float,formatted:?string,confidence:string} */
    public function geocode(string $address): array;

    /**
     * Coordinates → the nearest street address and the nearest named
     * intersection. Either may come back null: a highway shoulder has no
     * address, a rural road may have no crossing for miles. The coordinates
     * themselves are never at risk — they are stored before this is called.
     *
     * city/state/postal_code are the structured pieces of that address when
     * the driver can separate them (state as the 2-letter code), so a capture
     * can fill location fields the caller never typed. Null when unknown.
     *
     * @return array{address:?string,intersection:?string,city:?string,state:?string,postal_code:?string,confidence:string}
     */
    public function reverse(float $lat, float $lng): array;

    public function driverName(): string;
}

interface RoutePlanner
{
    /**
     * Drive route from one pin to another: actual road miles and minutes,
     * not straight-line distance. ok=false with a human-readable reason when
     * the driver cannot answer (unconfigured, no route, provider error) —
     * callers fall back to a hand-entered ETA, never to a guess.
     *
     * @return array{ok:bool,miles:?float,minutes:?int,reason:string}
     */
    public function route(float $fromLat, float $fromLng, float $toLat, float $toLng): array;

    public function driverName(): string;
}
