<?php
/*
 * Copyright (c) 2026 White Knight Roadside, LLC. All Rights Reserved.
 *
 * Proprietary and confidential. This software is LICENSED, NOT SOLD.
 * Unauthorized copying, modification, distribution, or use of this file,
 * via any medium, is strictly prohibited and will be prosecuted to the
 * fullest extent of the law (17 U.S.C. Sections 501-505). See LICENSE.txt.
 * Licensing: licensing@wkrllc.com
 */
declare(strict_types=1);

/**
 * Seeding is layered so a real install starts empty:
 *
 *   seed_core()      what the application cannot run without — the admin login,
 *                    settings, and the default markup tiers. No business data.
 *   seed_catalog()   the EXAMPLE products-and-services price book. Opt-in.
 *   seed_staff()     example dispatch/tech logins. Demo and tests only.
 *   seed_demo_data() example customers and jobs at every stage. Demo/tests only.
 *
 * seed_reference_data() is the everything wrapper the test suite uses: tests
 * need a full, known dataset — real installs do not.
 */
function seed_reference_data(bool $withDemo = true): void
{
    seed_core();
    seed_catalog();
    if ($withDemo) { seed_staff(); seed_demo_data(); }
}

function seed_core(): void
{
    $co   = App::config('company');
    $inst = App::config('install', []);

    foreach ([
        'company_name'    => $co['name'],
        'company_phone'   => $co['phone'],
        'company_email'   => $co['email'],
        'company_address' => 'Portland, OR',
        'tax_rate'        => '0',                     // Oregon has no sales tax
        'labor_rate'      => '125.00',
        'mileage_rate'    => '0.72',
        'estimate_terms'  => 'Customer authorizes the work described above and agrees to pay for the services and parts listed. Final invoice may vary if the scope of work changes.',
        'invoice_terms'   => 'Payment due on receipt. Parts carry the manufacturer warranty stated on their line; labour carries a 30-day workmanship warranty. Labour to replace a part under manufacturer warranty is billed at standard rates after the workmanship warranty has lapsed.',
        'invoice_footer'  => 'Final invoice may vary due to job scope changes.',
        'telnyx_api_key'  => '',
        'telnyx_from'     => '',
        'square_access_token' => '',
        'square_location_id'  => '',
        'square_environment'  => 'sandbox',
        'google_maps_key' => '',
        // Texted links (/sign, /locate, /pay) are built from this. Empty
        // falls back to the request host, which is right almost everywhere;
        // a production config generated by setup.php pins it explicitly.
        'app_base_url'    => (string) ($inst['base_url'] ?? ''),
    ] as $k => $v) {
        Db::insert('settings', ['skey' => $k, 'svalue' => (string) $v]);
    }

    // The one admin login the install seeds, so the application is usable on
    // first boot. Which of the two it is turns on a single question: did the
    // operator configure a real password?
    //
    //   password_hash set   — a REAL admin, from `php data/setup.php`. Seeded
    //                         under the configured name and address, NOT
    //                         flagged, never auto-retired. This is how a
    //                         public server comes up.
    //   password_hash empty — a TEMPORARY login at Rules::SETUP_EMAIL with a
    //                         published password, flagged is_setup. Creating
    //                         a real admin under Admin → Users deactivates it
    //                         (see Rules::retireSetupAdmins). Never deleted.
    //
    // The configured address is deliberately ignored in the temporary case:
    // seeding a real person's login with a known password is how the owner's
    // own account ends up marked disposable.
    $admin = (array) ($inst['admin'] ?? []);
    $hash  = (string) ($admin['password_hash'] ?? '');
    $real  = $hash !== '' && (string) ($admin['email'] ?? '') !== '';
    Db::insert('users', $real ? [
        'role'          => 'ADMIN',
        'first_name'    => (string) ($admin['first_name'] ?? '') !== '' ? (string) $admin['first_name'] : 'Admin',
        'last_name'     => (string) ($admin['last_name'] ?? '')  !== '' ? (string) $admin['last_name']  : 'User',
        'email'         => strtolower(trim((string) $admin['email'])),
        'phone_e164'    => phone_to_e164((string) $co['phone']),
        'password_hash' => $hash,
        'is_active' => 1, 'is_setup' => 0, 'can_accept_jobs' => 1, 'created_at' => now(),
    ] : [
        'role'          => 'ADMIN',
        'first_name'    => 'Setup',
        'last_name'     => 'Admin',
        'email'         => Rules::SETUP_EMAIL,
        'phone_e164'    => phone_to_e164((string) $co['phone']),
        'password_hash' => password_hash('admin123', PASSWORD_DEFAULT),
        'is_active' => 1, 'is_setup' => 1, 'can_accept_jobs' => 1, 'created_at' => now(),
    ]);

    // Parts markup matrix — industry-standard defaults (see Markup::DEFAULTS).
    if ((int) Db::val('SELECT COUNT(*) FROM markup_tiers') === 0) {
        $i = 0;
        foreach (Markup::DEFAULTS as [$min, $max, $pct]) {
            Db::insert('markup_tiers', [
                'min_cost'   => number_format($min, 2, '.', ''),
                'max_cost'   => $max === null ? null : number_format($max, 2, '.', ''),
                'markup_pct' => number_format($pct, 2, '.', ''),
                'sort_order' => $i++,
            ]);
        }
    }
}

/** Example dispatch and technician logins. Demo and test runs only. */
function seed_staff(): void
{
    foreach ([
        ['DISPATCH',   'Dana',   'Reyes', 'dispatch@wkrllc.com', 'dispatch123'],
        ['TECHNICIAN', 'Marcus', 'Hale',  'tech@wkrllc.com',     'tech123'],
    ] as [$role, $f, $l, $email, $pw]) {
        Db::insert('users', [
            'role' => $role, 'first_name' => $f, 'last_name' => $l, 'email' => $email,
            'phone_e164' => '+15037643154', 'password_hash' => password_hash($pw, PASSWORD_DEFAULT),
            'is_active' => 1, 'can_accept_jobs' => 1, 'created_at' => now(),
        ]);
    }
}

/** The EXAMPLE price book. A real install builds its own catalog at /catalog. */
function seed_catalog(): void
{
    foreach (catalog_seed_rows() as $i => $row) {
        Db::insert('catalog_items', ['sort_order' => $i] + $row);
    }
}

/**
 * THE PRICE BOOK, ONCE. Returns the seeded catalog as insert-ready rows keyed
 * by SKU — the single source for both seed_catalog(), which writes it at
 * install, and data/reconcile-catalog.php, which brings an already-installed
 * database back into line with it.
 *
 * Split out for exactly that second caller. The reconcile started life with
 * its own hand-written list of what had moved where, and that list was wrong
 * within a day: the battery *parts* were left in Roadside when the battery
 * *labour* moved to Mobile Repair, because nobody updating one list thought to
 * update the other. Two copies of the catalog is two catalogs.
 *
 * @return array<int, array<string,mixed>>
 */
function catalog_seed_rows(): array
{
    /* ---- Catalog. Pricing, warranties and account codes come from the
     *      pricing work in the source conversations.                       */
    /* Account codes below are the ones in Accounts::DEFAULTS and nothing else.
     * An earlier version of this seed used a per-service revenue tree (4010
     * Jump Start, 4020 Tire Change, 4200 Fuel...) that was never seeded into
     * gl_accounts, so every item here pointed at an account that did not
     * exist — and where the numbers happened to collide they collided WRONGLY:
     * a jump start posted to 4010, which is Parts Sales Revenue.
     *
     * The settled set is deliberately small: revenue is split by WHAT WAS SOLD
     * (labour / parts / fuel / fees), never by which service produced it.
     * Reporting by service is the job of service_category below, which is why
     * both columns exist.
     *
     * service_category is assigned by the demount test — see ServiceCategory.
     * Fees carry NO category: a call-out fee on a mechanic job is mechanic
     * revenue, so a fee inherits the category of the job it is billed on. */
    $catalog = [
        // sku, type, category, svcCategory, name, pricing, price, cost, uom, taxable, noVehicle, warrantyMo, rev, cogs
        /* ---- Roadside Services: hand tools, nothing comes apart. ---- */
        ['SVC-JUMP-STD',      'SERVICE','Jump Start','ROADSIDE','Jump Start — 12V',                       'FLAT',     85.00,   0,'job', 0,0, 0,'4000',''],
        ['SVC-LOCKOUT-STD',   'SERVICE','Lockout',   'ROADSIDE','Vehicle Lockout',                         'FLAT',     95.00,   0,'job', 0,0, 0,'4000',''],
        ['SVC-FUEL-GAS-2GAL', 'SERVICE','Fuel',      'ROADSIDE','Fuel Delivery — gasoline (2 gal incl.)',  'FLAT',     85.00,  12,'job', 0,0, 0,'4020','5090'],
        ['SVC-FUEL-DSL-5GAL', 'SERVICE','Fuel',      'ROADSIDE','Fuel Delivery — diesel (5 gal incl.)',    'FLAT',     85.00,  24,'job', 0,0, 0,'4020','5090'],
        // Tire work splits on the demount test, not on where the customer is.
        ['SVC-TIRE-CHANGE',   'SERVICE','Tire',      'ROADSIDE','Spare Tire Swap — donut',                 'FLAT',     85.00,   0,'job', 0,0, 0,'4000',''],
        // $115, not the $95 it started at. A shop charges ~$30 for the same
        // repair; the difference is that WKR brings it to the vehicle. Priced
        // above the spare swap by more than a token, because a plug is the
        // swap's wheel-off work PLUS the repair, carries materials, and is the
        // only roadside tire job that can come back as a warranty claim.
        ['SVC-TIRE-PLUG',     'SERVICE','Tire',      'ROADSIDE','Tire Repair — plug, tire stays on rim',   'FLAT',    115.00,   0,'job', 0,0, 0,'4000',''],

        /* ---- Advanced Tire Services: the bead comes off the rim. ---- */
        ['SVC-TIRE-PATCH',    'SERVICE','Tire',      'TIRE',    'Tire Repair — internal patch (demount)',  'FLAT',    125.00,   0,'job', 0,0, 0,'4000',''],
        // Sold as one job because that is how it is dispatched: the tire is
        // brought to the vehicle and fitted in the same visit. no_vehicle is
        // set so a loose wheel dropped off can be invoiced without a VIN.
        ['SVC-TIRE-DELIVERY', 'SERVICE','Tire',      'TIRE',    'Tire Delivery, Mount & Balance',          'FLAT',    150.00,   0,'job', 0,1, 0,'4000',''],
        ['SVC-MOUNT-BAL',     'SERVICE','Tire',      'TIRE',    'Mount & Balance — loose wheel',           'FLAT',    150.00,   0,'job', 0,1, 0,'4000',''],

        /* ---- Mobile Repair Services: a part comes off, a part goes on. ----
         * Battery work lives here rather than with the roadside kit. It is a
         * part sale with labour attached, it is sold standalone across the
         * trade, and grouping it with jump starts hid both facts. */
        ['SVC-DIAG-STD',      'SERVICE','Mechanic',  'MECHANIC','Mobile Diagnostic — 1 hour',              'FLAT',     85.00,   0,'job', 0,0, 0,'4000',''],
        ['SVC-BATT-TEST',     'SERVICE','Battery',   'MECHANIC','Battery & Charging System Test',          'FLAT',     45.00,   0,'job', 0,0, 0,'4000',''],
        ['SVC-BATT-INSTALL',  'SERVICE','Battery',   'MECHANIC','Battery Installation Labour',             'FLAT',     65.00,   0,'job', 0,0, 0,'4000',''],
        ['SVC-MECH-HOURLY',   'SERVICE','Mechanic',  'MECHANIC','Mobile Mechanic Labour',                  'HOURLY',  125.00,   0,'hour',0,0, 0,'4000',''],
        ['SVC-ALT-REPLACE',   'SERVICE','Mechanic',  'MECHANIC','Alternator Replacement — quote required', 'ESTIMATE',  0.00,   0,'job', 0,0, 0,'4000',''],
        ['SVC-STARTER-REPL',  'SERVICE','Mechanic',  'MECHANIC','Starter Replacement — quote required',    'ESTIMATE',  0.00,   0,'job', 0,0, 0,'4000',''],

        /* ---- Towing Services: the VEHICLE moves. ----
         * White Knight does not tow. These are seeded for tenants that do; an
         * operator who does not offer the category simply never rolls it.
         *
         * Posted to 4000 like every other service, NOT to a towing revenue
         * account. Splitting revenue by service is the mistake this file's
         * header describes — the per-service tree that pointed at accounts
         * nobody had seeded. "How much did towing make" is answered by
         * service_category, which is the column that exists for it. If an
         * operator genuinely wants tow revenue on its own GL line, that is an
         * account they add at /accounts, not a default shipped to everyone.
         *
         * Priced at 0.00 / ESTIMATE deliberately. Tow pricing is local — hook
         * fee plus per-mile, and the mileage varies by tenant — so a seeded
         * number here would be a guess presented as a rate. */
        ['SVC-WINCH-STD',     'SERVICE','Towing',    'TOWING',  'Winch Out — light duty',                  'FLAT',    150.00,   0,'job', 0,0, 0,'4000',''],
        ['SVC-TOW-FLATBED',   'SERVICE','Towing',    'TOWING',  'Flatbed Tow — hook fee, quote required',  'ESTIMATE',  0.00,   0,'job', 0,0, 0,'4000',''],
        ['SVC-TOW-STANDARD',  'SERVICE','Towing',    'TOWING',  'Standard Tow — hook fee, quote required', 'ESTIMATE',  0.00,   0,'job', 0,0, 0,'4000',''],

        /* ---- Other ---- */
        ['SVC-CONSULT-VIDEO', 'SERVICE','Consult',   'OTHER',   'Video Consultation — 20 min',             'FLAT',     35.00,   0,'job', 0,1, 0,'4000',''],

        ['FEE-CALLOUT',       'FEE','Fees','','Call-Out / Mobile Service Fee',          'FLAT',     65.00,   0,'job',  0,1, 0,'4030',''],
        ['FEE-MILEAGE',       'FEE','Fees','','Mileage',                                'PER_UNIT',  0.72,   0,'mile', 0,1, 0,'4030',''],
        ['FEE-DRIVETIME',     'FEE','Fees','','Drive Time — 65% of labour rate',        'HOURLY',   81.25,   0,'hour', 0,1, 0,'4030',''],
        ['FEE-AFTERHOURS',    'FEE','Fees','','After-Hours / Emergency Surcharge',      'FLAT',     40.00,   0,'job',  0,1, 0,'4030',''],
        ['FEE-SHOP-SUPPLY',   'FEE','Fees','','Shop Supplies',                          'FLAT',     15.00,   0,'job',  0,1, 0,'4030',''],
        ['FEE-CANCEL',        'FEE','Fees','','Cancellation Fee — after dispatch',      'FLAT',     65.00,   0,'job',  0,1, 0,'4030',''],
        ['FEE-NOSHOW',        'FEE','Fees','','Customer No-Show Fee',                   'FLAT',     65.00,   0,'job',  0,1, 0,'4030',''],
        ['FEE-TIRE-DISPOSAL', 'FEE','Fees','','Tire Disposal',                          'PER_UNIT',  7.00,   0,'tire', 0,1, 0,'4030',''],
        /* Not revenue. Money held against a returnable core — a liability.
         * PAIRED with the core_charge on the part line (16th column below):
         * Rules::coreDepositGate refuses to issue an invoice where the fee
         * lines on 2050 and the part lines' core charges disagree, because
         * one side billed without the other is either an untracked deposit
         * or a refund owed for money never collected. */
        ['FEE-CORE-DEPOSIT',  'FEE','Fees','','Core Deposit — refundable liability',    'PER_UNIT', 22.00,   0,'unit', 0,1, 0,'2050',''],
        // Fuel sold past what the delivery includes is still fuel revenue.
        ['FEE-FUEL-OVERAGE',  'FEE','Fees','','Fuel Overage — per gallon',              'PER_UNIT',  6.50,4.10,'gal', 0,1, 0,'4020','5090'],

        ['PRT-BATT-GRP24',    'PART','Battery', 'MECHANIC','Battery — Group 24F, 700 CCA',      'PER_UNIT',219.00,132.00,'unit',0,0,36,'4010','5000'],
        ['PRT-BATT-GRP35',    'PART','Battery', 'MECHANIC','Battery — Group 35, 640 CCA',       'PER_UNIT',199.00,119.00,'unit',0,0,36,'4010','5000'],
        // Reman parts carry the core charge (16th column) that pairs with
        // FEE-CORE-DEPOSIT above — the custody side of the same $22.
        ['PRT-ALT-STD',       'PART','Mechanic','MECHANIC','Alternator — remanufactured',       'PER_UNIT',289.00,205.00,'unit',0,0,24,'4010','5000', 0, 22.00],
        ['PRT-STARTER-STD',   'PART','Mechanic','MECHANIC','Starter — remanufactured',          'PER_UNIT',249.00,172.00,'unit',0,0,24,'4010','5000', 0, 22.00],
        ['PRT-TIRE-VALVE',    'PART','Tire',    'TIRE',    'Valve Stem',                        'PER_UNIT',  6.00,  1.10,'unit',0,0, 0,'4010','5000'],
        ['PRT-TIRE-PATCH',    'PART','Tire',    'TIRE',    'Tire Patch Kit',                    'PER_UNIT', 18.00,  4.25,'unit',0,0, 0,'4010','5000'],
        ['PRT-FUEL-GAS-GAL',  'PART','Fuel',    'ROADSIDE','Gasoline — per gallon',             'PER_UNIT',  6.50,  4.10,'gal', 0,1, 0,'4020','5090'],

        /* ---- The miscellaneous charge slot (is_misc, the 15th column) ----
         * Not a product. It is the one sanctioned way to bill something the
         * catalog has no SKU for — most often extra labour a job turned out to
         * need. Whoever adds it must type what it is for, and that sentence
         * becomes the line's name on the customer document.
         *
         * Seeded at 0.00 / ESTIMATE because there is no such thing as a
         * standard price for it, and markup-exempt because it is priced by
         * judgement at the moment of sale rather than from a cost. A cost may
         * still be entered against it — a sublet, a part bought off the shelf —
         * which is why the COGS account is 5010 rather than blank.
         *
         * Seeded TAXABLE, which the hourly-labour SKUs are not. That is a
         * deliberate operator choice, not a rule. Note that taxability is a
         * property of the SLOT, not of the line: Lines::add() snapshots
         * catalog_items.taxable and the add-line form offers no per-line
         * toggle. An operator who needs both behaviours adds a second misc
         * slot rather than expecting to untick one charge. At Oregon's 0% rate
         * the distinction costs nothing; in a taxing state, revisit it. */
        ['MISC-CHARGE',       'SERVICE','Misc',   'OTHER',   'Miscellaneous Charge',              'ESTIMATE',  0.00,  0.00,'job', 1,1, 0,'4000','5010', 1],
    ];
    $out = [];
    foreach ($catalog as $r) {
        $out[] = [
            'sku' => $r[0], 'item_type' => $r[1], 'category' => $r[2],
            'service_category' => $r[3], 'name' => $r[4],
            'description' => '', 'pricing_model' => $r[5], 'unit_price' => $r[6], 'unit_cost' => $r[7],
            'uom' => $r[8], 'taxable' => $r[9], 'vehicle_not_required' => $r[10],
            'warranty_months' => $r[11],
            /* Optional 16th column: the refundable core charge on a reman
             * part. Zero for everything that has no returnable core. */
            'core_charge' => $r[15] ?? 0,
            'revenue_account' => $r[12], 'cogs_account' => $r[13],
            'is_active' => 1,
            /* Optional 15th column; every real product omits it. */
            'is_misc' => $r[14] ?? 0,
        ];
    }
    return $out;
}

function seed_demo_data(): void
{
    $sku = fn(string $s): int => (int) Db::val('SELECT id FROM catalog_items WHERE sku = ?', [$s]);

    $provider = Db::insert('customers', [
        'customer_type' => 'COMMERCIAL', 'company' => 'Cascade Motor Club',
        'first_name' => 'Dispatch', 'last_name' => 'Desk', 'phone_e164' => '+15035550142',
        'email' => 'dispatch@cascademotorclub.example', 'city' => 'Portland', 'state' => 'OR',
        'is_provider' => 1, 'provider_code' => 'CMC-2026', 'payment_terms' => 'NET_30',
        'created_at' => now(), 'updated_at' => now(),
    ]);

    // A business account WITHOUT net terms: creating a commercial account
    // changes nothing about payment — COD until credit is deliberately granted.
    Db::insert('customers', [
        'customer_type' => 'FLEET', 'company' => 'Rose City Property Management',
        'first_name' => 'Marcy', 'last_name' => 'Holt', 'phone_e164' => '+15035550171',
        'email' => 'facilities@rosecitypm.example', 'city' => 'Portland', 'state' => 'OR',
        'payment_terms' => 'DUE_ON_RECEIPT',
        'created_at' => now(), 'updated_at' => now(),
    ]);

    $cids = [];
    foreach ([
        ['INDIVIDUAL','Rachel','Nguyen','',  '+15035550188','rachel.nguyen@example.com','Beaverton',1],
        ['INDIVIDUAL','Tom',   'Bradley','', '+15035550119','tbradley@example.com',     'Gresham',  1],
    ] as $p) {
        $cids[] = Db::insert('customers', [
            'customer_type' => $p[0], 'first_name' => $p[1], 'last_name' => $p[2], 'company' => $p[3],
            'phone_e164' => $p[4], 'email' => $p[5], 'city' => $p[6], 'state' => 'OR',
            'sms_approved' => $p[7], 'sms_consent_at' => $p[7] ? now() : null,
            'sms_consent_source' => $p[7] ? 'verbal_at_intake' : null,
            'created_at' => now(), 'updated_at' => now(),
        ]);
    }

    // Check digits verified.
    $vids = [];
    foreach ([
        [$cids[0], '1HGCM82633A004352', 'XKR482',  'OR', 2003, 'Honda',  'Accord', 'Silver'],
        [$cids[1], '5TFDY5F1XDX293412', 'TRK9921', 'OR', 2013, 'Toyota', 'Tundra', 'White'],
    ] as $v) {
        $vids[] = Db::insert('vehicles', [
            'customer_id' => $v[0], 'vin' => $v[1], 'plate' => $v[2], 'plate_state' => $v[3],
            'year' => $v[4], 'make' => $v[5], 'model' => $v[6], 'color' => $v[7],
            'vin_decoded' => json_encode(Integrations::vin()->decode($v[1])), 'created_at' => now(),
        ]);
    }

    $terms = (string) App::setting('estimate_terms', '');

    /* ---- Job 1: closed out and paid. Runs the whole chain. -------------- */
    $sr1 = Db::insert('service_requests', [
        'doc_number' => DocNumber::next('SER'), 'channel' => 'PHONE', 'customer_id' => $cids[0],
        'status' => 'COMPLETED', 'job_source' => 'RETAIL', 'priority' => 'URGENT',
        'reported_name' => 'Rachel Nguyen', 'reported_phone' => '+15035550188', 'reported_service' => 'JUMPSTART',
        'reported_problem' => 'Car will not start after sitting three days. Dome light is dim.',
        'reported_location' => '12800 SW Canyon Rd', 'city' => 'Beaverton', 'state' => 'OR', 'postal_code' => '97005',
        'latitude' => 45.4977, 'longitude' => -122.8003,
        'v_year' => 2003, 'v_make' => 'Honda', 'v_model' => 'Accord', 'v_color' => 'Silver',
        'v_plate' => 'XKR482', 'v_plate_state' => 'OR', 'comms_consent' => 1, 'created_by' => 1,
        'created_at' => now(), 'updated_at' => now(),
    ]);
    $est1 = Db::insert('estimates', [
        'doc_number' => DocNumber::next('EST'), 'service_request_id' => $sr1, 'customer_id' => $cids[0],
        'vehicle_id' => $vids[0], 'status' => 'APPROVED', 'service_type' => 'JUMPSTART',
        'scope_summary' => 'Jump start, then test the battery and charging system.',
        /* nearest_address, not service_address: the old column was retired in
         * favour of nearest_address and fresh installs never get it, so the
         * seed writing it crashed every --demo install. See the estimates
         * comment in app/Schema.php and data/drop-service-address.php. */
        'nearest_address' => '12800 SW Canyon Rd', 'city' => 'Beaverton', 'state' => 'OR',
        'tax_rate' => 0, 'authorized_by' => 'Rachel Nguyen', 'authorization_method' => 'VERBAL',
        'authorized_at' => now(), 'authorization_ip' => '127.0.0.1', 'terms_text' => $terms,
        'created_at' => now(), 'updated_at' => now(),
    ]);
    Lines::add('EST', $est1, $sku('SVC-JUMP-STD'), 1);
    Lines::add('EST', $est1, $sku('FEE-CALLOUT'), 1);
    Lines::add('EST', $est1, $sku('SVC-BATT-TEST'), 1);
    EstimateController::recalc(Db::one('SELECT * FROM estimates WHERE id = ?', [$est1]));

    $wo1 = Db::insert('work_orders', [
        'doc_number' => DocNumber::next('WOR'), 'estimate_id' => $est1, 'service_request_id' => $sr1,
        'technician_id' => 3, 'status' => 'COMPLETED', 'outcome_code' => 'COMPLETED',
        'assigned_at' => now(), 'en_route_at' => now(), 'on_site_at' => now(), 'completed_at' => now(),
        'field_notes' => 'Battery tested at 9.8V under load — failed. Jump started, advised replacement.',
        'signer_name' => 'Rachel Nguyen', 'signed_at' => now(), 'created_at' => now(), 'updated_at' => now(),
    ]);
    Lines::copy('EST', $est1, 'WO', $wo1);

    $inv1 = Db::insert('invoices', [
        'doc_number' => DocNumber::next('INV'), 'service_request_id' => $sr1, 'estimate_id' => $est1,
        'work_order_id' => $wo1, 'customer_id' => $cids[0], 'vehicle_id' => $vids[0],
        'status' => 'ISSUED', 'tax_rate' => 0, 'issued_at' => now(),
        'terms' => 'DUE_ON_RECEIPT',                       // retail: COD, due the day it issued
        'due_at' => Rules::invoiceDueAt(now(), 'DUE_ON_RECEIPT'),
        'created_at' => now(), 'updated_at' => now(),
    ]);
    Lines::copy('WO', $wo1, 'INV', $inv1);
    $t = Lines::totals('INV', $inv1, 0.0);
    $pay1 = Db::insert('payments', [
        'doc_number' => DocNumber::next('PAY'), 'invoice_id' => $inv1, 'customer_id' => $cids[0],
        'method' => 'CARD', 'amount' => $t['total'], 'tip_amount' => 20.00, 'processor' => 'manual',
        'idempotency_key' => 'seed-' . $inv1, 'status' => 'COMPLETED', 'paid_at' => now(), 'created_at' => now(),
    ]);
    Db::insert('receipts', [
        'doc_number' => DocNumber::next('RCT'), 'payment_id' => $pay1,
        'invoice_id' => $inv1, 'issued_at' => now(),
    ]);
    InvoiceController::recalc(Db::one('SELECT * FROM invoices WHERE id = ?', [$inv1]));

    /* ---- Job 2: technician on scene right now. -------------------------- */
    $sr2 = Db::insert('service_requests', [
        'doc_number' => DocNumber::next('SER'), 'channel' => 'PHONE', 'customer_id' => $cids[1],
        'status' => 'ACCEPTED', 'job_source' => 'RETAIL', 'priority' => 'STANDARD',
        'reported_name' => 'Tom Bradley', 'reported_phone' => '+15035550119', 'reported_service' => 'TIRE_SWAP',
        'reported_problem' => 'Right rear flat. Spare is under the bed, customer has the key.',
        'reported_location' => 'NE Division St & 182nd Ave', 'city' => 'Gresham', 'state' => 'OR',
        'v_year' => 2013, 'v_make' => 'Toyota', 'v_model' => 'Tundra', 'v_color' => 'White',
        'v_plate' => 'TRK9921', 'v_plate_state' => 'OR',
        'promised_eta' => date('Y-m-d H:i:s', time() + 2400), 'comms_consent' => 1, 'created_by' => 1,
        'created_at' => now(), 'updated_at' => now(),
    ]);
    $est2 = Db::insert('estimates', [
        'doc_number' => DocNumber::next('EST'), 'service_request_id' => $sr2, 'customer_id' => $cids[1],
        'vehicle_id' => $vids[1], 'status' => 'APPROVED', 'service_type' => 'TIRE_SWAP',
        'po_number' => 'TB-2026-0117',
        'scope_summary' => 'Change the right rear to the spare.',
        /* Cross streets are not an address — "NE Division St & 182nd Ave" is
         * where the truck is standing, not somewhere to post a letter, so it
         * goes in nearest_intersection and the address stays empty. Exactly
         * the shape a real intersection job has, which is what demo data is
         * for. (Also the service_address retirement — see job 1.) */
        'nearest_intersection' => 'NE Division St & 182nd Ave', 'city' => 'Gresham', 'state' => 'OR',
        'tax_rate' => 0, 'authorized_by' => 'Tom Bradley', 'authorization_method' => 'SMS',
        'authorized_at' => now(), 'terms_text' => $terms, 'created_at' => now(), 'updated_at' => now(),
    ]);
    Lines::add('EST', $est2, $sku('SVC-TIRE-CHANGE'), 1);
    Lines::add('EST', $est2, $sku('FEE-CALLOUT'), 1);
    EstimateController::recalc(Db::one('SELECT * FROM estimates WHERE id = ?', [$est2]));

    $wo2 = Db::insert('work_orders', [
        'doc_number' => DocNumber::next('WOR'), 'estimate_id' => $est2, 'service_request_id' => $sr2,
        'po_number' => 'TB-2026-0117',
        'technician_id' => 3, 'status' => 'ON_SITE', 'assigned_at' => now(),
        'en_route_at' => now(), 'on_site_at' => now(), 'created_at' => now(), 'updated_at' => now(),
    ]);
    Lines::copy('EST', $est2, 'WO', $wo2);

    /* ---- Job 3: provider dispatch received electronically, untouched.
     *      Exactly the case the Service Request exists for.                 */
    Db::insert('service_requests', [
        'doc_number' => DocNumber::next('SER'), 'channel' => 'PROVIDER_API',
        'status' => 'PENDING', 'job_source' => 'PROVIDER', 'provider_id' => $provider,
        'provider_ref' => 'CMC-884120', 'priority' => 'EMERGENCY',
        'reported_name' => 'A. Souza', 'reported_phone' => '+15035550164', 'reported_service' => 'LOCKOUT',
        'reported_problem' => 'Keys locked inside. Caller reports a dog in the vehicle.',
        'reported_location' => '2185 NW 185th Ave', 'city' => 'Hillsboro', 'state' => 'OR', 'postal_code' => '97124',
        'v_year' => 2011, 'v_make' => 'Ford', 'v_model' => 'F-150', 'v_color' => 'Blue',
        'v_plate' => 'LAND12', 'v_plate_state' => 'OR',
        'promised_eta' => date('Y-m-d H:i:s', time() + 1800), 'comms_consent' => 1,
        'intake_notes' => 'Animal inside — treat as emergency. Advise the fire department if the animal is in distress.',
        'created_by' => 1, 'created_at' => now(), 'updated_at' => now(),
    ]);

    /* ---- Job 4: a raw phone call. Half a name, vague location. ---------- */
    Db::insert('service_requests', [
        'doc_number' => DocNumber::next('SER'), 'channel' => 'PHONE',
        'status' => 'PENDING', 'job_source' => 'RETAIL', 'priority' => 'STANDARD',
        'reported_name' => 'Derek (last name unclear)', 'reported_phone' => '+15035550177',
        'reported_service' => 'FUEL',
        'reported_problem' => 'Out of fuel on the shoulder. Gasoline. Says about a quarter mile past the exit.',
        'reported_location' => 'I-84 EB near Exit 9', 'city' => 'Portland', 'state' => 'OR',
        'comms_consent' => 0, 'created_by' => 1, 'created_at' => now(), 'updated_at' => now(),
    ]);

    foreach ([
        ['NAPA Auto Parts', 'Parts & Materials', '5000', 'Group 24F battery — stock', 132.00, date('Y-m-d')],
        ['Chevron',         'Vehicle Fuel',      '5030', 'Service van fuel',            78.40, date('Y-m-d', strtotime('-2 day'))],
        ['Telnyx',          'SMS Messaging',     '6150', 'Monthly messaging',           14.00, date('Y-m-d', strtotime('-5 day'))],
    ] as $x) {
        Db::insert('expenses', [
            'doc_number' => DocNumber::next('EXP'), 'vendor_name' => $x[0], 'category' => $x[1],
            'account_code' => $x[2], 'description' => $x[3], 'amount' => $x[4], 'tax_amount' => 0,
            'expense_date' => $x[5], 'payment_method' => 'CARD', 'created_at' => now(),
        ]);
    }

    // A couple of outbox entries so the messaging screen is not empty.
    Sms::queue(Db::one('SELECT * FROM customers WHERE id = ?', [$cids[1]]), 'dispatch',
        ['{eta}' => date('g:i A', time() + 2400), '{total}' => '', '{doc}' => ''], $sr2);
    Sms::queue(Db::one('SELECT * FROM customers WHERE id = ?', [$cids[0]]), 'receipt',
        ['{doc}' => 'RCT-' . date('Ymd') . '-001', '{total}' => money(195), '{eta}' => ''], $sr1);
}
